### ISSUE TITLE
BUG - bitOrder element have maxOccurs=1

### ISSUE THREAD

**Issue by ergozeller** [SmartgridReady/SGrSpecifications#141]
**Describe the bug**
on `modbusInterfaceDescription` the `bitOrder` element is allowed multiple times. We do not support multiple conversion schemes at the same time on the same device.

**Expected behavior**
the `bitOrder` element should occure exactly once

**Comment by ChrisBroenni** [comment]
thanks. Pls. make sure that bitorder, wordswap etc, are still possible in parallel
