### ISSUE TITLE
iopBooleanMapper has been removed  URGENT

### ISSUE THREAD

**Issue by ChrisBroenni** [SmartgridReady/SGrSpecifications#178]
**Describe the bug**
 Modbus attribute has been removed and blocks completion of the Hoval heatpump process.

                <iopBooleanMapper>
                  <assignedValueMeans>false</assignedValueMeans>
                  <value>255</value>
                </iopBooleanMapper>

please reinstall schema and Java handling

@ArndGerns 
@ergo-furrer 

**Expected behavior**
A value of 255 means that the boolean is set to false , other mean true

**why**
Some Modbus devices use inverted boolean logic. In this case, the heatpump team decided not to show error numbers but true = in error

**Comment by ArndGerns** [comment]
Hallo Chris,

ok – wenn es das braucht, dann braucht es das.

Hans und ich haben uns das angeschaut. Wir würden das eher explizit beim boolean angeben, anstatt einen Mapper zu definieren:

```
<modbusDataPointConfiguration>
  <modbusDataType>
    <boolean>
      <falseValue>255</falseValue>
    </boolean>
  </modbusDataType>
```

oder

```
<modbusDataPointConfiguration>
  <modbusDataType>
    <boolean>
      <trueValue>255</trueValue>
    </boolean>
  </modbusDataType>
```

oder default mit 0=false
 
```
<modbusDataPointConfiguration>
  <modbusDataType>
    <boolean />
  </modbusDataType>
```

da es ja eher zum Datentyp gehört.

Viele Grüsse,
Arnd.
