### ISSUE TITLE
Support RestAPI RW

### ISSUE THREAD

**Issue by ArndGerns** [SmartGridready/SGrSpecifications#293]
Currently, it is only possible to define one `restApiServiceCall` for  RestAPI datapoint - but with this only datapoints with only R=Read or W=Write can be supported.

This must be extended, so that two `restApiServiceCall` are possible.

Due to compatibility, the `restApiServiceCall` must be retained.

So possible combinations are
- only `restApiServiceCall` (old version)
- only `restApiReadServiceCall` for R datapoints
- only `restApiWriteServiceCall` for W datapoints
- both `restApiReadServiceCall` and `restApiWriteServiceCall` for RW datapoints

**Comment by mkrebs81** [comment]
since this has been implemented quite some time ago, I am closing this issue now.
