### ISSUE TITLE
Add mapping for value for RestAPI

### ISSUE THREAD

**Issue by ArndGerns** [SmartGridready/SGrSpecifications#295]
Add mapping for value for RestAPI.

It should be able to have a mapping for read and write for a rest api datapoint.

Example:
```
<valueMapping>
  <mapping>
    <from>off</from>
    <to>false</to>
  </mapping>
  <mapping>
    <from>on</from>
    <to>true</to>
  </mapping>
</valueMapping>
```

For a write data call, the generic value is mapped with the mapping and the mapped value is written to the rest api.

For a read data call, the value is read from the rest api and then mapped to the generic value.

**Comment by mkrebs81** [comment]
I suggest closing this issue, or are there further changes necessary?

**Comment by ergo-furrer** [comment]
> I suggest closing this issue, or are there further changes necessary?

Closed.
