### ISSUE TITLE
additional Modbus attributes and features, request for documentation workflow inclusion

### ISSUE THREAD

**Issue by ChrisBroenni** [SmartgridReady/SGrSpecifications#86]
**generic**
_1) new SGrDataPointDescriptionType : SGrNamelistType:sEN17609Name_
_2) new text element: SGrDataPointDescriptionType.SGrLegibDocumentationType elemnt: dpPrgDesc_

**Modbus**
_1) new  SGrModbusLayer6DeviationType  2RegBase1000_L2H,2RegBase1000_H2L,SGReadyEnum2IO_L2H_
   element of LegibDesc
_2) new  **SGrModbusEnumMapperType**_
          Enumerations typically define operation modes or singlular states. Devices use different control schemes, SmartGridrady defines a commmon information model for interoperable behaviour.
          At interface class level, enums may use different binary values. 
            **modbusEnumMapper** uses indexes as the value of the generic definition, the value of shows the proprietary value.
           (Write data direction)
           **genEnumMapper**  uses indexes as the  value of the proprietary definition, the value shows the generic value
           (Read data direction)
		   This value is index of the enum list representation of the bit
			**0** means BIT0
			**65535** means DO NOT MAP, UNKNOWN 

_3) new  **SGrModbusBitmapMapperType**_
          Bitmaps typically define operation modes or parallel active states. Devices use different control schemes, SmartGridrady defines a commmon information model for interoperable behaviour.
          At interface class level, Bitmaps may use different binary values. 
            **modbusBitMapper** uses indexes as the value of the generic definition, the value of shows the proprietary value.
           (Write data direction)
           **genBitMapper**  uses indexes as the  value of the proprietary definition, the value shows the generic value
           (Read data direction)

_4) new  **SGrModbusBooleanMapperType**_
          Booleans at modbus level may be true if 1, 0, 0xff, -1 , all but not a certain value .
          **isPositiveLogic** is _true_ if a number must contain a specific value to be valid
          **isPositiveLogic** is _false_ if a number must contain any  but NOT a specific value to be valid  
          **value**  contains the value for the defined logic selected

**Comment by ergozeller** [comment]
Assessment:
- Addition of EN17609Name to NameList is already done on master.
- Extenstions of bitmaps and enums are done in #111 

Nothing further left to do. Issue can be closed.

**Comment by ChrisBroenni** [comment]
generic
2) new text element: SGrDataPointDescriptionType.SGrLegibDocumentationType elemnt: dpPrgDesc

Is still open

**Comment by ergozeller** [comment]
Fixed in #120 , but additionally needs a release of the SGrWebApp to https://library.smartgridready.ch
