### ISSUE TITLE
REQ - API implementation to query generic attributes

### ISSUE THREAD

**Issue by ergo-furrer** [SmartgridReady/SGrSpecifications#99]
## User Voice
While implementing the API read SGr generic attributes in SGrJava some minor issues within the XSD have been found.

### Suggested Solution
The SGrAttr4GenericType has minOccurs="0" maxOccurs="unbounded" for the functional profiles and the data points. This is not  necessary, since the container is defined to wrap all possible attributes in a sequence.

### Alternatives (optional)
Define minOccurs="0", maxOccurs="1"
Fix some typos

## Acceptance Criteria
It is not possible to add more than one SGrAttr4GenericType container per device, functional-profile and data-point.

**Comment by ergozeller** [comment]
Implemented in #120
